### ISSUE TITLE
app is crashing on entering the if(whatToDo.equals(null)) loop

### ISSUE THREAD

**Issue by MayurKomar** [MayurKomar/github-slideshow#5]
[verify.txt](https://github.com/MayurKomar/github-slideshow/files/4870171/verify.txt)

**Comment by MayurKomar** [comment]
the app is crashing on entering the if(whatToDo.equals(null)) loop

**Comment by MayurKomar** [comment]
2020-07-03 19:47:15.447 3775-3775/com.example.planmytrip E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.planmytrip, PID: 3775
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.example.planmytrip.VerifyNo$3.onComplete(VerifyNo.java:120)
        at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:919)

**Comment by MayurKomar** [comment]
this is the exception from logcat
